config/routes.rb
Rails.application.routes.draw do
  resources :bills
  resources :intitutions
  resources :enrollments
  resources :students
  resources :institutions
  root 'home#index'
end

app/models/institution.rb
class Institution < ApplicationRecord
  has_many :enrollments
  validates :name, presence: true, uniqueness: true
  validates :cnpj, numericality: { only_integer: true }, length: {is: 14}, uniqueness: true
  validates :institution_type, inclusion: { in: %w[Universidade Escola Creche] }
end

app/controllers/institutions_controller.rb
class InstitutionsController < ApplicationController
  before_action :set_institution, only: %i[ show edit update destroy ]

  # GET /institutions or /institutions.json
  def index
    @institutions = Institution.all
  end

  # GET /institutions/1 or /institutions/1.json
  def show
  end

  # GET /institutions/new
  def new
    @institution = Institution.new
  end

  # GET /institutions/1/edit
  def edit
  end

  # POST /institutions or /institutions.json
  def create
    @institution = Institution.new(institution_params)

    respond_to do |format|
      if @institution.save
        format.html { redirect_to institution_url(@institution), notice: "Institution was successfully created." }
        format.json { render :show, status: :created, location: @institution }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutions/1 or /institutions/1.json
  def update
    respond_to do |format|
      if @institution.update(institution_params)
        format.html { redirect_to institution_url(@institution), notice: "Institution was successfully updated." }
        format.json { render :show, status: :ok, location: @institution }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @institution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutions/1 or /institutions/1.json
  def destroy
    @institution.destroy

    respond_to do |format|
      format.html { redirect_to institutions_url, notice: "Institution was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institution
      @institution = Institution.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def institution_params
      params.require(:institution).permit(:name, :cnpj, :institution_type)
    end
end

app/helpers/institutions_helper.rb
module InstitutionsHelper
end

app/views/institutions/_form.html.erb
<%= form_with(model: institution) do |form| %>
  <% if institution.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(institution.errors.count, "error") %> prohibited this institution from being saved:</h2>

      <ul>
        <% institution.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="forms forms-institution">
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="grid_column_2">
    <%= form.label :cnpj, style: "display: block" %>
    <%= form.text_field :cnpj %>
  </div>

  <div class="grid_span_2">
    <%= form.label :institution_type, style: "display: block" %>
    <%= form.select :institution_type, ["Universidade", "Escola", "Creche"], { prompt: "Select a Student" }, { class: "select_institution" } %>
  </div>

  <div class="forms-button">
    <%= link_to "Cancel", :back, class:"button button-cancel" %>
  </div>

  <div class="forms-button">
    <%= form.submit "Confirm", class:"button button-confirm" %>
  </div>
</div>
<% end %>

app/views/institutions/_institution.html.erb
<div class="centralized">
  <h1>Institution Info</h1>

  <div class="show">
    <div class="show_institution_name">
      <h2><%= institution.name %></h2>
    </div>

    <div class="grid_column_1 show_infos">
      <strong>Name</strong>
      <p><%= institution.name %></p>
    </div>

    <div class="grid_column_2 show_infos">
      <strong>CNPJ</strong>
      <p><%= institution.cnpj %></p>
    </div>

    <div class="grid_column_3 show_infos">
      <strong>Type</strong>
      <p><%= institution.institution_type %></p>
    </div>
  </div>

  <hr>

  <% if Enrollment.where(institution_id: institution.id).present? %>
    <h2 style="text-align:left">Students</h2>

    <hr>

    <div class="institution_students">
      <div class="table">
        <table>
          <thead>
            <tr>
              <th>Name</th>
              <th>CPF</th>
              <th>Birth Date</th>
              <th>Phone</th>
              <th>Gender</th>
              <th>Bill Payment Type</th>
              <th colspan="3">Actions</th>
            </tr>
          </thead>
  <% end %>
          <tbody>
            <% Enrollment.where(institution_id: institution.id).each do |enrollment|%>
              <tr>
                <td><%= enrollment.student.name %></td>
                <td><%= enrollment.student.cpf %></td>
                <td><%= enrollment.student.birth_date.strftime("%d/%m/%Y") %></td>
                <td><%= enrollment.student.phone %></td>
                <td><%= enrollment.student.gender %></td>
                <td><%= enrollment.student.bill_payment_type %></td>
                <td><%= link_to "Show", enrollment.student, class:"button button-show" %></td>
                <td><%= link_to "Edit", edit_student_path(enrollment.student) , class:"button button-edit" %></td>
                <td><%= button_to "Destroy", enrollment.student, form: {data: {turbo_confirm: "Are you sure?"}}, method: :delete %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
</div>

app/views/institutions/edit.html.erb
<h1>Editing institution</h1>

<%= render "form", institution: @institution %>

<br>

<div>
  <%= link_to "Show this institution", @institution %> |
  <%= link_to "Back to institutions", institutions_path %>
</div>

app/views/institutions/index.html.erb
<div class="tables">
  <h1>Institutions</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>CNPJ</th>
        <th>Type</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @institutions.each do |institution|%>
        <tr>
          <td><%= institution.name %></td>
          <td><%= institution.cnpj %></td>
          <td><%= institution.institution_type %></td>
          <td><%= link_to "Show", institution, class:"button button-show" %></td>
          <td><%= link_to "Edit", edit_institution_path(institution) , class:"button button-edit" %></td>
          <td><%= button_to "Destroy", institution, form: {data: {turbo_confirm: "Are you sure?"}}, method: :delete %></td>   
        </tr>
      <% end %>
    </tbody>
    <tfoot>
      <tr>
        <th colspan="6"><%= link_to "+ New institution", new_institution_path %></th>
      </tr>
    </tfoot>
  </table>
</div>

app/views/institutions/new.html.erb
<h1>New institution</h1>

<%= render "form", institution: @institution %>

<br>

<div>
  <%= link_to "Back to institutions", institutions_path %>
</div>

app/views/institutions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @institution %>

<div>
  <%= link_to "Edit this institution", edit_institution_path(@institution) %> |
  <%= link_to "Back to institutions", institutions_path %>

  <%= button_to "Destroy this institution", @institution, method: :delete %>
</div>