config/routes.rb
Rails.application.routes.draw do
  resources :bills
  resources :intitutions
  resources :enrollments
  resources :students
  resources :institutions
  root 'home#index'
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :enrollment
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: %i[ show edit update destroy ]

  # GET /bills or /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1 or /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills or /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to bill_url(@bill), notice: "Bill was successfully created." }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1 or /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to bill_url(@bill), notice: "Bill was successfully updated." }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1 or /bills/1.json
  def destroy
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url, notice: "Bill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bill_params
      params.require(:bill).permit(:bill_value, :due_date, :enrollment_id, :bill_status)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_bill.html.erb
<div id="<%= dom_id bill %>">
  <p>
    <strong>Bill value:</strong>
    <%= bill.bill_value %>
  </p>

  <p>
    <strong>Due date:</strong>
    <%= bill.due_date %>
  </p>

  <p>
    <strong>Enrollment:</strong>
    <%= bill.enrollment_id %>
  </p>

  <p>
    <strong>Bill status:</strong>
    <%= bill.bill_status %>
  </p>

</div>

app/views/bills/_form.html.erb
<%= form_with(model: bill) do |form| %>
  <% if bill.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
        <% bill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :bill_value, style: "display: block" %>
    <%= form.text_field :bill_value %>
  </div>

  <div>
    <%= form.label :due_date, style: "display: block" %>
    <%= form.date_field :due_date %>
  </div>

  <div>
    <%= form.label :enrollment_id, style: "display: block" %>
    <%= form.text_field :enrollment_id %>
  </div>

  <div>
    <%= form.label :bill_status, style: "display: block" %>
    <%= form.text_field :bill_status %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render "form", bill: @bill %>

<br>

<div>
  <%= link_to "Show this bill", @bill %> |
  <%= link_to "Back to bills", bills_path %>
</div>

app/views/bills/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="tables">
  <h1>Bills</h1>

  <table>
    <thead>
      <tr>
        <th>Value</th>
        <th>Due Date</th>
        <th>Status</th>
        <th>Enrollment ID</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @bills.each do |bill|%>
        <tr>
          <td><%= bill.bill_value.round(2) %></td>
          <td><%= bill.due_date.strftime("%d/%m/%Y") %></td>
          <td><%= bill.bill_status %></td>
          <td><%= bill.enrollment_id %></td>
          <td><%= link_to "Edit", edit_bill_path(bill) %></td>
          <td><%= button_to "Destroy", bill, form: {data: {turbo_confirm: "Are you sure?"}}, method: :delete %></td>       
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render "form", bill: @bill %>

<br>

<div>
  <%= link_to "Back to bills", bills_path %>
</div>

app/views/bills/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bill %>

<div>
  <%= link_to "Edit this bill", edit_bill_path(@bill) %> |
  <%= link_to "Back to bills", bills_path %>

  <%= button_to "Destroy this bill", @bill, method: :delete %>
</div>