config/routes.rb
Rails.application.routes.draw do
  resources :bills
  resources :intitutions
  resources :enrollments
  resources :students
  resources :institutions
  root 'home#index'
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  after_create :create_bills

  belongs_to :institution
  belongs_to :student
  has_many :bills
  validates :full_value, numericality: { greater_than: 0 }
  validates :installments, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :due_day,
            numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 31 }
  validates :course_name, presence: true

  private

  def create_bills
    CreateEnrollmentBills.perform(self)
  end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :set_enrollment, only: %i[ show edit update destroy ]

  # GET /enrollments or /enrollments.json
  def index
    @enrollments = Enrollment.all
  end

  # GET /enrollments/1 or /enrollments/1.json
  def show
  end

  # GET /enrollments/new
  def new
    @enrollment = Enrollment.new
  end

  # GET /enrollments/1/edit
  def edit
  end

  # POST /enrollments or /enrollments.json
  def create
    @enrollment = Enrollment.create(enrollment_params)

    respond_to do |format|
      if @enrollment.save
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully created." }
        format.json { render :show, status: :created, location: @enrollment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrollments/1 or /enrollments/1.json
  def update
    respond_to do |format|
      if @enrollment.update(enrollment_params)
        format.html { redirect_to enrollment_url(@enrollment), notice: "Enrollment was successfully updated." }
        format.json { render :show, status: :ok, location: @enrollment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @enrollment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrollments/1 or /enrollments/1.json
  def destroy
    @enrollment.destroy

    respond_to do |format|
      format.html { redirect_to enrollments_url, notice: "Enrollment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enrollment
      @enrollment = Enrollment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def enrollment_params
      params.require(:enrollment).permit(:full_value, :installments, :due_day, :course_name, :institution_id, :student_id)
    end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/_enrollment.html.erb
<div class="centralized">
  <h1>Enrollment Info</h1>

  <div class="show">
    <div class="show_enrollment_name">
      <h2><%= enrollment.course_name %> - <%= enrollment.student.name %></h2>
    </div>

    <div class="grid_column_1 show_infos">
      <strong>ID</strong>
      <p><%= enrollment.id %></p>
    </div>

    <div class="grid_column_2 show_infos">
      <strong>Full Value</strong>
      <p><%= enrollment.full_value %></p>
    </div>

    <div class="grid_column_3 show_infos">
      <strong>Installments</strong>
      <p><%= enrollment.installments %></p>
    </div>

    <div class="grid_column_1 show_infos">
      <strong>Due Day</strong>
      <p><%= enrollment.due_day %></p>
    </div>

    <div class="grid_column_2 show_infos">
      <strong>Institution Name</strong>
      <p><%= enrollment.institution.name %></p>
    </div>
  </div>

  <hr>

  <h2 style="text-align:left">Bills</h2>

  <hr>

  <div class="enrollment_students">
    <div class="table">
      <table>
        <thead>
          <tr>
            <th>ID</th>
            <th>Value</th>
            <th>Due Date</th>
            <th>Status</th>
            <th colspan="1">Actions</th>
          </tr>
        </thead>
          <tbody>
            <% enrollment.bills.each do |bill|%>
              <tr>
                <td><%= bill.id %></td>
                <td><%= bill.bill_value.round(2) %></td>
                <td><%= bill.due_date.strftime("%d/%m/%Y") %></td>
                <td><%= bill.bill_status %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
</div>

app/views/enrollments/_form.html.erb
<%= form_with(model: enrollment) do |form| %>
  <% if enrollment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(enrollment.errors.count, "error") %> prohibited this enrollment from being saved:</h2>

      <ul>
        <% enrollment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="forms forms-enrollment">
    <div>
      <%= form.label :full_value, style: "display: block" %>
      <%= form.text_field :full_value %>
    </div>

    <div class="grid_column_2">
      <%= form.label :installments, style: "display: block" %>
      <%= form.number_field :installments %>
    </div>

    <div>
      <%= form.label :due_day, style: "display: block" %>
      <%= form.number_field :due_day %>
    </div>

    <div>
      <%= form.label :course_name, style: "display: block" %>
      <%= form.text_field :course_name %>
    </div>

    <div>
      <%= form.label :institution_id, style: "display: block" %>
      <%= form.select :institution_id, Institution.all.map { |institution| [institution.name, institution.id] }, { prompt: "Select a Institution" }, { class: "select_institution" } %>
    </div>

    <div>
      <%= form.label :student_id, style: "display: block" %>
      <%= form.select :student_id, Student.all.map { |student| [student.name, student.id] }, { prompt: "Select a Student" }, { class: "select_institution" } %>
    </div>

    <div class="forms-button">
      <%= link_to "Cancel", :back, class:"button button-cancel" %>
    </div>

    <div class="forms-button">
      <%= form.submit "Confirm", class:"button button-confirm" %>
    </div>
  </div>

<% end %>

app/views/enrollments/edit.html.erb
<h1>Editing enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Show this enrollment", @enrollment %> |
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="tables">
  <h1>Enrollments</h1>

  <table>
    <thead>
      <tr>
        <th>Full Value</th>
        <th>Installments</th>
        <th>Due Day</th>
        <th>Course Name</th>
        <th>Institution<//th>
        <th>Student</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @enrollments .each do |enrollment|%>
        <tr>
          <td><%= enrollment.full_value %></td>
          <td><%= enrollment.installments %></td>
          <td><%= enrollment.due_day %></td>
          <td><%= enrollment.course_name %></td>
          <td><%= enrollment.institution.name %></td>
          <td><%= enrollment.student.name %></td>
          <td><%= link_to "Show", enrollment, class:"button button-show" %></td>
          <td><%= link_to "Edit", edit_enrollment_path(enrollment) , class:"button button-edit" %></td>
          <td><%= button_to "Destroy", enrollment, form: {data: {turbo_confirm: "Are you sure?"}}, method: :delete %></td>    
        </tr>
        <% if enrollment == @enrollments.last %>
          <tr>
            <td colspan="9"><%= link_to "+ New enrollment", new_enrollment_path, class:"link_new" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/enrollments/new.html.erb
<h1>New enrollment</h1>

<%= render "form", enrollment: @enrollment %>

<br>

<div>
  <%= link_to "Back to enrollments", enrollments_path %>
</div>

app/views/enrollments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @enrollment %>

<div>
  <%= link_to "Edit this enrollment", edit_enrollment_path(@enrollment) %> |
  <%= link_to "Back to enrollments", enrollments_path %>

  <%= button_to "Destroy this enrollment", @enrollment, method: :delete %>
</div>